### ISSUE TITLE
Think About Global Variables

### ISSUE THREAD

**Issue by davegoopot** [glitch-game-club/simple-game-to-edit#12]
In the spirit of being code that encourages beginners to experiment with we choose to keep global variables visible at the top of the source file. There is however a different between global variables that are obvious how they are used, e.g. `var gravity = 500;` and those that are boiler plate and might do to be hidden, e.g. `var wlevel;`.

This issue is to somehow emphasise "useful" global variables and hide the other ones.

**Comment by mickfuzz** [comment]
Hi there, 

I agree with you here. And I think this got cleared up in code changes after our discussions. 
I think there is another factor which is worth thinking about for these 'global variables' - which is will they be useful when debugging. 

I've started to use the debugger in firefox (great) and also chrome (a bit less easy but workable). You can set watch points and then watch the variable values. 
I can only really get this to work for the global variables mentioned at the start. So there's a factor there too.
