### ISSUE TITLE
Make the Player "Speed Up" Amount Into a Varaible

### ISSUE THREAD

**Issue by davegoopot** [glitch-game-club/simple-game-to-edit#13]
Pull out the number from `player.body.velocity.x = -100;` so that the curious player might change this as well as the gravity constant.

**Comment by mickfuzz** [comment]
I do like this but also think about encouraging players to dive deeper into the code as per the game cards here https://drive.google.com/file/d/1iL9fPP_ntsktGyBpX7u7-kTCnFuCDjdR/view?usp=sharing

I think there is a bit a of a trade off here between teaching game mechanics via pulling  out the variable to the top, and then encouraging searching and finding more authentic variable in real contexts. If we can create experiences which start with the former and move towards the latter than I think that's ideal. 

What we lose here is familiarity with concepts like x and y axis, velocity as a phaser keyword, visual recognition of if statements . Which I think if fine for this short activity but just something to keep in mind.

**Comment by mickfuzz** [comment]
fixed by #11
